### PR TITLE
feat: support all PlatformPayButton props on Android, reduce library size

### PR DESCRIPTION
**Pull request by charliecruzan-stripe**
## Summary

Updates to use the new google pay button API, meaning we don't need to upgrade our asset files anymore 🎉 also this improves library size because we remove >200 XML assets

## library size decrease

before:
```
package size:  829.8 kB
unpacked size: 4.0 MB
```

after:

```
package size:  256.5 kB
unpacked size: 1.7 MB
```

## Testing

- [x] I tested this manually
- [ ] I added automated tests

## Documentation

Select one: 
- [x] I have added relevant documentation for my changes.
- [ ] This PR does not result in any developer-facing changes.

### CODE REVIEW

**Comment by gregavola** [comment]
@charliecruzan-stripe Any idea when this will be released? I'm currently blocked by Google Pay API acceptance, as they need the new button UI.

**Comment by bilal-korir** [comment]
> @charliecruzan-stripe Any idea when this will be released? I'm currently blocked by Google Pay API acceptance, as they need the new button UI.

The same here. Our app's screen background is dark and it seems the `appearance={PlatformPay.ButtonStyle.White}` on android is not working. Google Pay API team rejected our request, because the button doesn't look nice due to colors contrast issue.

If you can publish this update to NPM/Yarn will be much appreciated. Thank you guys for your work.

**Comment by charliecruzan-stripe** [comment]
deployed in v0.34.0!

**Comment by bilal-korir** [comment]
> deployed in v0.34.0!

You're the best, thank you @charliecruzan-stripe

**Pull request merged**
