### PR TITLE
fix: make data param nullable for onActivityResult on android

### PR DESCRIPTION
**Pull request by experiment322**
It seems that the code using this param handled the possibility for `data` to be `null`, but it wasn't declared as a nullable type.

Encountered a crash while playing with another library which also spawned some activity which can return no data (ie `data = null`), but even so, it seemed that this param should've been declared with a nullable type.

### CODE REVIEW

**Comment by thorsten-stripe** [comment]
I think this might have been resolved by https://github.com/stripe/stripe-react-native/pull/255 @arekkubaczkowski can you take a look?

**Comment by arekkubaczkowski** [comment]
> I think this might have been resolved by #255 @arekkubaczkowski can you take a look?

I think it's unrelated, I am fine to merge this PR

**Comment by thorsten-stripe** [comment]
Thanks @experiment322 . Could you please sign the CLA?

**Review by arekkubaczkowski — APPROVED** [review]

**Comment by experiment322** [comment]
@thorsten-stripe, I've already signed it. I don't know why it's reported that it isn't signed. Does it need some kind of approval from someone?

**Comment by thorsten-stripe** [comment]
@experiment322 looks like maybe an issue with email address difference, see message above: https://github.com/stripe/stripe-react-native/pull/252#issuecomment-845939162

**Comment by experiment322** [comment]
Fixed

**Pull request merged**
