### PR TITLE
fix: expo config plugin version

### PR DESCRIPTION
**Pull request by charliecruzan-stripe**
## Summary
closes https://github.com/stripe/stripe-react-native/issues/1108

## Testing

- [x] I tested this manually
- [ ] I added automated tests

## Documentation

Select one: 
- [ ] I have added relevant documentation for my changes.
- [x] This PR does not result in any developer-facing changes.

### CODE REVIEW

**Comment by RdC1965** [comment]
I've seen that this fix solves the problem. However, it was added in version 0.19.0, and whenever I install it (expo SDK 46.0.16) I subsequently receive the following message:

> Some dependencies are incompatible with the installed expo package version:
>  - @stripe/stripe-react-native - expected version: 0.13.1 - actual version installed: 0.19.0

**Comment by Olli2** [comment]
+1 Same problem here

**Comment by kmehner** [comment]
+1 Same problem here

**Comment by GSolari79** [comment]
Do we have any news? I cannot develop with expo SDK46 and cannot have the @expo/config-plugins@^5.0.0 dependency that is required by this SDK.

**Comment by charliecruzan-stripe** [comment]
To get this fix, you'll need to use v0.19.0, which means you will need to upgrade your expo SDK to 47 (46 still uses 0.13.1)

**Pull request merged**
