### PR TITLE
add missing 3ds button props

### LINKED ISSUE #182: Colors set in `threeDSecureParams` are mostly ignored
I tried setting the main color (themeColors.brandBlue) everywhere I could, but the only thing that changed is the text in the middle - that's the colour everything that is now violet should have. How can I achieve that?

```js
<StripeProvider
  publishableKey={key}
  threeDSecureParams={{
    backgroundColor: '#FFFFFF', // iOS only
    timeout: 5,
    label: {
      headingTextColor: themeColors.brandBlue,
      headingFontSize: 13
    },
    navigationBar: {
      headerText: 'Complete card authentication',
      statusBarColor: themeColors.brandBlue // Android only
    },
    footer: {
      // iOS only
      backgroundColor: themeColors.brandBlue,
      headingTextColor: '#FFFFFF',
      textColor: '#FFFFFF'
    },
    submitButton: {
      backgroundColor: themeColors.brandBlue,
      borderRadius: 0,
      textColor: '#FFFFFF',
      textFontSize: 14
    }
  }}>
  <Component />
</StripeProvider>
```

### LINKED ISSUE #201: Colors set for buttons in `threeDSecureParams` are ignored on iOS
@benomatis reported in (https://github.com/stripe/stripe-react-native/issues/182) that the 3DS2 buttons on iOS are not set correctly from the `threeDSecureParams`.

To fix this:
* In the [mappers](https://github.com/stripe/stripe-react-native/blob/251b8f9a6de8853277993a6ce3c8bc25c132687e/ios/Mappers.swift#L466), the RN SDK will need to call setButtonCustomization, as it's currently only making a copy of the button customization and then mutating it.
* The mapper will also need to offer a way to customize STPThreeDSCustomizationButtonType.cancel, as it currently only modifies the confirm button.

### PR DESCRIPTION
**Pull request by arekkubaczkowski**
resolves #201 
resolves #182

### CODE REVIEW

**Comment by thorsten-stripe** [comment]
@arekkubaczkowski can you post yyour `threeDSecureParams` object? I have

```js
threeDSecureParams: {
            backgroundColor: '#800080', // iOS only
            timeout: 5,
            label: {
              headingTextColor: '#FFC0CB',
              headingFontSize: 13,
            },
            navigationBar: {
              headerText: '3d secure',
            },
            footer: {
              backgroundColor: '#800080', // iOS only
            },
            submitButton: {
              backgroundColor: '#800080',
              borderRadius: 12,
              textColor: '#FFC0CB',
              textFontSize: 14,
            },
          },
```

But it does not seem to work for the button

image
image

**Comment by arekkubaczkowski** [comment]
@thorsten-stripe  because for  `complete authentication` you have to set styles for `continueButton`, this is how it's named on native side also

**Review by thorsten-stripe — APPROVED** [review]
LGTM, thanks

**Comment by benomatis** [comment]
@arekkubaczkowski can you still post your `threeDSecureParams` object please? Will the doc be updated? Would it not be practical if the doc actually had ALL options listed?

**Comment by arekkubaczkowski** [comment]
@benomatis all of the properties are listed in API reference https://stripe.dev/stripe-react-native/api-reference/interfaces/threedsecureconfigurationparams.html
docs will be updated with the new release version, @thorsten-stripe  am I right?

**Comment by arekkubaczkowski** [comment]
here you can find available props for now: https://github.com/stripe/stripe-react-native/blob/master/src/types/ThreeDSecure.ts#L1

**Comment by benomatis** [comment]
@arekkubaczkowski Thank you, we'll only need the doc to be updated then.

**Comment by benomatis** [comment]
@arekkubaczkowski This is now working great, thank you so much!

**Comment by benomatis** [comment]
@arekkubaczkowski I use dark mode on my phone, and it appears to make the bottom gray part (with Learn more... and Need help) to be really dark, like if there was an overlay above it, but it's not, if I tap it, it works fine, it's just very dark. Any way that could be overriden? Interestingly the very top gray line, just above the popup, remains the same gray. Shall I open a separate issue for this?

**Comment by arekkubaczkowski** [comment]
>Shall I open a separate issue for this?

please do and provide some screenshots

**Comment by benomatis** [comment]
image

**Comment by benomatis** [comment]
> > Shall I open a separate issue for this?
> 
> please do and provide some screenshots

ok, I will

**Comment by benomatis** [comment]
@arekkubaczkowski https://github.com/stripe/stripe-react-native/issues/248 thanks!

**Pull request merged**
